version: '3'
services:
  service1:
    build:
      context: ./service1  
    ports:
      - "3000:3000" 
    environment:
      - NODE_ENV=production
    networks:
      - backend

  service2:
    build:
      context: ./service2  
    ports:
      - "4000:4000"  
    environment:
      - NODE_ENV=production
    networks:
      - backend

  service3:
    build:
      context: ./service3  
    ports:
      - "5000:5000" 
    environment:
      - NODE_ENV=production
    networks:
      - backend

networks:
  backend:
    driver: bridge
