version: '3.8'

services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        service_name: service1
    ports:
      - "3000:3000"
    networks:
      - my_network

  service2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        service_name: service2
    ports:
      - "3001:3001"
    networks:
      - my_network

  service3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        service_name: service3
    ports:
      - "3002:3002"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
