version: '3'

services:
  microservice1:
    build: ./microservice1
    ports:
      - "3001:3001"
    
  microservice2:
    build: ./microservice2
    ports:
      - "3002:3002"

  microservice3:
    build: ./microservice3
    ports:
      - "3003:3003"
